choco install vlc -y
choco install git.install -y
choco install 7zip.install -y
choco install notepadplusplus.install -y
choco install googlechrome -y
choco install discord.install -y
choco install anaconda3 -y
choco install zoom -y
choco install putty.install -y
choco install vscode.install -y
choco install itunes -y
choco install spotify -y
choco install winscp.install -y
choco install googledrive -y
choco install azure-cli -y
choco install youtube-dl -y
choco install audacity -y
choco install calibre -y
choco install dbeaver -y
choco install kdenlive -y
choco install xnview -y
choco install handbrake -y
choco install vnc-viewer -y
choco install whatsapp -y
choco install obs-studio -y
choco install qbittorrent -y
choco install sharex -y
choco install realvnc -y
choco install office365business -y
choco install gom-player -y
choco install teracopy -y
choco install openvpn-connect -y
choco install bluescreenview.install -y
choco install treesizefree -y
choco install spacesniffer -y
choco install bulkrenameutility -y
choco install mobaxterm -y
choco install sourcetree -y
choco install chrome-remote-desktop-host -y
choco install sql-server-management-studio
